import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'

import styles from '../styles/Home.module.css'


let AuthExample = dynamic(() => import('../components/auth_example'), {
  ssr: false,
})

const Home: NextPage = () => {

  let [example, setExample] = useState<'ui' | 'code'>('ui')

  return (
    <div>
      <Head>
        <title>Vulpo Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav className={styles['header-nav']}>

          <a href="https://github.com/riezler-co/auth">Github</a>
        </nav>

        <div className={styles['header-bottom']}>
          <h2 className={styles.name}>Vulpo Auth</h2>
          <p className={styles['header-info']}>
            Vulpo Auth is a complete authentication solution for your single page application, it comes as a single binary that you can host anywhere and modular SDKs for you to create a unique authentication experiences.
          </p>
        </div>
      </header>

      <main className={styles.content}>
        <section className={styles.hero}>
          <h1 className={styles['hero-title']}>
            Effortless Authentication for your Web Application.
          </h1>
          <a href="#" className={`button ${styles['get-started']}`}>Get Started</a>
        </section>

        <section>
          <header>
            <h2>Drop-in UI</h2>

            <div>
              <button onClick={() => setExample('ui')}>UI</button>
              <button onClick={() => setExample('code')}>Code</button>
            </div>
          </header>
          <div className={styles['ui-example']} suppressHydrationWarning={true}>
            { (process.browser && example === 'ui') &&
              <AuthExample />
            }
            { example === 'code' &&
              <pre style={{ color: '#fff' }}>
                { process.env.exampleCode }
              </pre>
            }
          </div>
        </section>

        <section>
          <h2>Get Started</h2>
        </section>
      </main>
    </div>
  )
}

export default Home
