version: '2'

services:
  postgres:
    image: postgres
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 6543:5432
    volumes:
      - postgres-data:/var/lib/postgres

  mailhog:
    image: mailhog/mailhog
    container_name: auth_mailhog
    restart: always
    ports:
      - 7654:1025
      - 8025:8025
    volumes:
      - mailhog-data:/var/lib/mailhog


volumes:
  postgres-data:
  mailhog-data:
