[package]
name = "vulpo"
version = "0.1.0"
authors = ["Michael Riezler <michaelriezler@gmail.com>"]
edition = "2018"
description = "Core SDK for use with the Vulpo authentication server"
license="MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
jsonwebtoken = "7.2.0"
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tokio = { version="1.10.1", features=["macros"] }